name: Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Mount cache
        id: mount-cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cache/poetry
          key: poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-
      
      - name: Create cache directory and retrieve directory uid
        id: create-cache-dir
        run: |
          mkdir -p ${{ github.workspace }}/.cache/poetry
          echo "uid=$(id -u $(stat -c "%U" ${{ github.workspace }}/.cache/poetry))" >> $GITHUB_OUTPUT

      -
        name: Linting
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: mpc:lint
          target: lint
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-contexts: poetry_cache=${{ github.workspace }}/.cache/poetry
          build-args: UID=${{ steps.create-cache-dir.outputs.uid }}
      
      -
        name: Testing
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: mpc:test
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-contexts: poetry_cache=${{ github.workspace }}/.cache/poetry
          build-args: UID=${{ steps.create-cache-dir.outputs.uid }}

      -
        name: Format checking
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: mpc:format-check
          target: format-check
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-contexts: poetry_cache=${{ github.workspace }}/.cache/poetry
          build-args: UID=${{ steps.create-cache-dir.outputs.uid }}
      
      - name: List files in cache
        run: find ${{ github.workspace }}/.cache/poetry