name: Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: mpc:lint-test-latest
          target: lint-test
          cache-from: type=gha
          cache-to: type=gha,mode=max
